// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arquivei_api.Context;

namespace arquivei_api.Migrations
{
    [DbContext(typeof(ArquiveiContext))]
    [Migration("20210428113530_remove_id_from_nfe")]
    partial class remove_id_from_nfe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("arquivei_api.Models.Nfe", b =>
                {
                    b.Property<string>("AccessKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccessKey");

                    b.ToTable("Nfes");
                });
#pragma warning restore 612, 618
        }
    }
}
